# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the IDE and the
# command line.

# Include a set of recommended lints for Flutter apps, packages, and plugins
# to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project, it can also be
  # suppressed for a single line of code or a specific Dart file by using
  # `// ignore: name_of_lint` or `// ignore_for_file: name_of_lint` syntax.
  rules:
    # Enforce the use of const constructors where possible
    prefer_const_constructors: true
    # Ensure const constructors are used in immutable classes
    prefer_const_constructors_in_immutables: true
    # Prefer const literals for creating immutable lists and maps
    prefer_const_literals_to_create_immutables: true
    # Encourage the use of const for variable declarations where possible
    prefer_const_declarations: true

    # Additional helpful rules
    # Prefer single quotes over double quotes for strings
#    prefer_single_quotes: true
    # Avoid using unnecessary Container widgets
    avoid_unnecessary_containers: true
    # Use SizedBox instead of Container for spacing purposes
    sized_box_for_whitespace: true
    # Require keys in widget constructors for better widget identification
    use_key_in_widget_constructors: true
    # Prefer final fields in classes to enforce immutability
    prefer_final_fields: true
    # Prefer final local variables to prevent unnecessary reassignments
    prefer_final_locals: true
    # Remove unnecessary const keywords
    unnecessary_const: true
    # Remove unnecessary 'new' keywords
    unnecessary_new: true
    # Avoid using print statements in production code
    avoid_print: true

    # Performance-related rules
    # Avoid using function literals in forEach calls for better performance
    avoid_function_literals_in_foreach_calls: true
    # Prefer using isEmpty over checking length == 0
    prefer_is_empty: true
    # Prefer using isNotEmpty over checking length > 0
    prefer_is_not_empty: true